version: '3.8'

services:
  medcare-control-tower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medcare_pharma_control_tower
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
