import {
  AlertTriangle,
  Check,
  CheckCircle2,
  Download,
  ExternalLink,
  FileText,
  PackageCheck,
  ScanLine,
  Truck,
  XCircle,
} from 'lucide-react';
import Drawer from '../../ui/Drawer';
import Button from '../../ui/Button';
import StatusBadge from '../../ui/StatusBadge';
import { cn } from '../../../lib/utils';
import { formatINR } from '../../../lib/utils';
import type { PaymentRequest } from '../../../data/mockData';
import type { ThreeWayMatchDetails } from '../../../data/threeWayMatch';

interface Props {
  open: boolean;
  onClose: () => void;
  details: ThreeWayMatchDetails;
  payment: PaymentRequest;
  onApprove: (p: PaymentRequest) => void;
  onReject: (p: PaymentRequest) => void;
  onReview: (p: PaymentRequest) => void;
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return <h3 className="text-[13px] font-semibold tracking-tight text-brand-charcoal">{children}</h3>;
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 py-1">
      <span className="text-[12px] text-brand-charcoal/50">{label}</span>
      <span className="text-[12.5px] font-medium text-brand-charcoal">{value}</span>
    </div>
  );
}

export default function ThreeWayMatchDrawer({ open, onClose, details, payment, onApprove, onReject, onReview }: Props) {
  const isMatch = details.kind !== 'Mismatch';
  const first = details.items[0];
  const matchedQty = first.grnQty;

  const downloadInvoice = () => {
    const lines = [
      'PharmaNexus — Supplier Invoice (demo)',
      '------------------------------------------',
      `Invoice : ${details.invoiceNumber}`,
      `Supplier: ${details.supplier}`,
      `PO ref  : ${details.poNumber}`,
      `GRN ref : ${details.grnNumber}`,
      `Date    : ${details.invoiceDate}`,
      ...details.items.map((i) => `${i.medicine} — ${i.invoiceQty} units × ${formatINR(i.unitPrice)} = ${formatINR(i.invoiceQty * i.unitPrice)}`),
      `Subtotal : ${formatINR(details.charges.subtotal)}`,
      `GST      : ${formatINR(details.charges.gst)}`,
      `Logistics: ${formatINR(details.charges.logistics)}`,
      `Total    : ${formatINR(details.charges.total)}`,
      '------------------------------------------',
      'Demo invoice generated by PharmaNexus.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${details.invoiceNumber}.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <Drawer
      open={open}
      onClose={onClose}
      title="3 Way Match Details"
      subtitle={`${details.poNumber} + ${details.grnNumber} + ${details.invoiceNumber}`}
      width="lg"
      footer={
        <div className="flex w-full flex-wrap items-center justify-end gap-2">
          <Button variant="secondary" onClick={() => onReview(payment)} disabled={payment.status === 'Paid'}>
            Request Review
          </Button>
          <Button variant="danger" onClick={() => onReject(payment)} disabled={payment.status === 'Paid'}>
            <XCircle size={14} /> Reject
          </Button>
          <Button onClick={() => onApprove(payment)} disabled={payment.status === 'Paid'}>
            <CheckCircle2 size={14} /> Approve Payment
          </Button>
        </div>
      }
    >
      <div className="space-y-5">
        <div className="flex items-center justify-between rounded-xl border border-brand-navy/10 bg-brand-navy/[0.02] px-4 py-3">
          <div>
            <p className="text-[12px] text-brand-charcoal/50">3 Way Match status</p>
            <p className="text-[14px] font-semibold text-brand-charcoal">
              {details.poNumber} + {details.grnNumber} + {details.invoiceNumber}
            </p>
          </div>
          <StatusBadge
            status={details.kind}
            tone={isMatch ? 'success' : 'danger'}
          />
        </div>

        {/* Purchase Order */}
        <div className="rounded-xl border border-brand-navy/10 p-4">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-navy/5 text-brand-muted">
                <Truck size={15} />
              </span>
              <div>
                <SectionTitle>Purchase Order</SectionTitle>
                <p className="font-mono text-[13px] font-semibold text-brand-charcoal">{details.poNumber}</p>
              </div>
            </div>
            <Button variant="ghost" size="sm" onClick={() => onClose()}>
              <ExternalLink size={13} /> View Purchase Order
            </Button>
          </div>
          <div className="mt-3 grid grid-cols-2 gap-3">
            <InfoRow label="Supplier" value={details.supplier} />
            <InfoRow label="Order Date" value={details.orderDate} />
          </div>
          <table className="mt-2 w-full text-left text-[12.5px]">
            <thead>
              <tr className="border-b border-brand-navy/8 text-[10.5px] font-semibold tracking-wide text-brand-charcoal/45 uppercase">
                <th className="py-1.5">Medicine</th>
                <th className="py-1.5 text-right">Ordered Qty</th>
                <th className="py-1.5 text-right">Unit Price</th>
              </tr>
            </thead>
            <tbody>
              {details.items.map((i) => (
                <tr key={i.medicine} className="border-b border-brand-navy/5">
                  <td className="py-2 font-medium text-brand-charcoal">{i.medicine}</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{i.poQty} units</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{formatINR(i.unitPrice)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Goods Receipt */}
        <div className="rounded-xl border border-brand-navy/10 p-4">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-navy/5 text-brand-muted">
                <PackageCheck size={15} />
              </span>
              <div>
                <SectionTitle>Goods Receipt</SectionTitle>
                <p className="font-mono text-[13px] font-semibold text-brand-charcoal">{details.grnNumber}</p>
              </div>
            </div>
            <StatusBadge status={details.grnStatus} tone={details.grnStatus === 'Fully Received' ? 'success' : 'warning'} />
          </div>
          <InfoRow label="Received Date" value={details.receivedDate} />
          <table className="mt-2 w-full text-left text-[12.5px]">
            <thead>
              <tr className="border-b border-brand-navy/8 text-[10.5px] font-semibold tracking-wide text-brand-charcoal/45 uppercase">
                <th className="py-1.5">Medicine</th>
                <th className="py-1.5 text-right">PO Qty</th>
                <th className="py-1.5 text-right">Received Qty</th>
              </tr>
            </thead>
            <tbody>
              {details.items.map((i) => (
                <tr key={i.medicine} className="border-b border-brand-navy/5">
                  <td className="py-2 font-medium text-brand-charcoal">{i.medicine}</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{i.poQty} units</td>
                  <td className="py-2 text-right tabular-nums font-semibold text-brand-charcoal">{i.grnQty} units</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="mt-3 flex items-center justify-between rounded-lg bg-brand-navy/[0.03] px-3 py-2.5">
            <p className="text-[12px] font-medium text-brand-charcoal/70">
              {first.grnQty} of {first.poQty} units received
            </p>
            <p className="text-[12px] text-brand-charcoal/50">
              Remaining: <span className="font-semibold text-brand-charcoal">{details.pendingUnits} units</span>
            </p>
          </div>
        </div>

        {/* Invoice */}
        <div className="rounded-xl border border-brand-navy/10 p-4">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-navy/5 text-brand-muted">
                <ScanLine size={15} />
              </span>
              <div>
                <SectionTitle>Invoice</SectionTitle>
                <p className="font-mono text-[13px] font-semibold text-brand-charcoal">{details.invoiceNumber}</p>
              </div>
            </div>
            <div className="flex gap-1">
              <Button variant="ghost" size="sm" onClick={() => onClose()}>
                <FileText size={13} /> View Invoice
              </Button>
              <Button variant="ghost" size="sm" onClick={downloadInvoice}>
                <Download size={13} /> Download
              </Button>
            </div>
          </div>
          <div className="mt-3 grid grid-cols-2 gap-3">
            <InfoRow label="Supplier" value={details.supplier} />
            <InfoRow label="Invoice Date" value={details.invoiceDate} />
          </div>
          <table className="mt-2 w-full text-left text-[12.5px]">
            <thead>
              <tr className="border-b border-brand-navy/8 text-[10.5px] font-semibold tracking-wide text-brand-charcoal/45 uppercase">
                <th className="py-1.5">Medicine</th>
                <th className="py-1.5 text-right">Invoice Qty</th>
                <th className="py-1.5 text-right">Unit Price</th>
              </tr>
            </thead>
            <tbody>
              {details.items.map((i) => (
                <tr key={i.medicine} className="border-b border-brand-navy/5">
                  <td className="py-2 font-medium text-brand-charcoal">{i.medicine}</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{i.invoiceQty} units</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{formatINR(i.unitPrice)}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <dl className="mt-3 space-y-1.5 border-t border-brand-navy/8 pt-3 text-[12.5px]">
            <div className="flex justify-between text-brand-charcoal/60">
              <dt>Subtotal</dt>
              <dd className="tabular-nums">{formatINR(details.charges.subtotal)}</dd>
            </div>
            <div className="flex justify-between text-brand-charcoal/60">
              <dt>GST</dt>
              <dd className="tabular-nums">{formatINR(details.charges.gst)}</dd>
            </div>
            <div className="flex justify-between text-brand-charcoal/60">
              <dt>Logistics</dt>
              <dd className="tabular-nums">{formatINR(details.charges.logistics)}</dd>
            </div>
            <div className="flex justify-between border-t border-brand-navy/8 pt-1.5 text-[13.5px] font-semibold text-brand-charcoal">
              <dt>Total</dt>
              <dd className="tabular-nums">{formatINR(details.charges.total)}</dd>
            </div>
          </dl>
        </div>

        {/* Match Comparison */}
        <div
          className={cn(
            'rounded-xl border p-4',
            isMatch ? 'border-status-success/30 bg-status-successBg/30' : 'border-status-danger/30 bg-status-dangerBg/30',
          )}
        >
          <div className="flex items-center gap-2">
            {isMatch ? <CheckCircle2 size={16} className="text-status-success" /> : <AlertTriangle size={16} className="text-status-danger" />}
            <SectionTitle>Match Comparison</SectionTitle>
          </div>
          <table className="mt-3 w-full text-left text-[12.5px]">
            <thead>
              <tr className="border-b border-brand-navy/8 text-[10.5px] font-semibold tracking-wide text-brand-charcoal/45 uppercase">
                <th className="py-1.5">Medicine</th>
                <th className="py-1.5 text-right">Purchase Order</th>
                <th className="py-1.5 text-right">Goods Receipt</th>
                <th className="py-1.5 text-right">Invoice</th>
              </tr>
            </thead>
            <tbody>
              {details.items.map((i) => (
                <tr key={i.medicine} className="border-b border-brand-navy/5">
                  <td className="py-2 font-medium text-brand-charcoal">{i.medicine}</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{i.poQty} units</td>
                  <td className="py-2 text-right tabular-nums text-brand-charcoal/80">{i.grnQty} units</td>
                  <td
                    className={cn(
                      'py-2 text-right font-semibold tabular-nums',
                      i.invoiceQty !== i.grnQty ? 'text-status-danger' : 'text-status-success',
                    )}
                  >
                    {i.invoiceQty} units
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="mt-3 rounded-lg bg-white/70 px-3 py-2.5">
            <p className={cn('text-[12.5px] font-semibold', isMatch ? 'text-status-success' : 'text-status-danger')}>
              {isMatch ? '✓ Valid Partial Match' : '⚠ Mismatch Detected'}
            </p>
            <p className="mt-0.5 text-[12.5px] leading-relaxed text-brand-charcoal/70">{details.reason}</p>
            {details.pendingUnits > 0 && (
              <p className="mt-0.5 text-[12.5px] text-brand-charcoal/55">{details.pendingUnits} units remain pending delivery.</p>
            )}
          </div>
        </div>

        {/* Financial match */}
        <div className="rounded-xl border border-brand-navy/10 p-4">
          <SectionTitle>Financial Match</SectionTitle>
          <div className="mt-2 space-y-1.5 text-[12.5px]">
            <div className="flex justify-between text-brand-charcoal/60">
              <span>Purchase Order</span>
              <span className="tabular-nums">
                {first.grnQty} × {formatINR(first.unitPrice)} = <span className="font-semibold text-brand-charcoal">{formatINR(details.charges.subtotal)}</span>
              </span>
            </div>
            <div className="flex justify-between text-brand-charcoal/60">
              <span>Invoice</span>
              <span className="tabular-nums">
                {first.invoiceQty} × {formatINR(first.unitPrice)} = <span className="font-semibold text-brand-charcoal">{formatINR(first.invoiceQty * first.unitPrice)}</span>
              </span>
            </div>
            <div className="flex justify-between text-brand-charcoal/60">
              <span>Additional Charges (GST + Logistics)</span>
              <span className="tabular-nums">{formatINR(details.charges.gst + details.charges.logistics)}</span>
            </div>
            <div className="flex justify-between border-t border-brand-navy/8 pt-1.5 text-[13px] font-semibold text-brand-charcoal">
              <span>Amount Being Approved</span>
              <span className="tabular-nums">{formatINR(details.charges.total)}</span>
            </div>
          </div>
        </div>

        {/* Payment being approved */}
        <div className="rounded-xl bg-brand-navy p-4 text-white">
          <SectionTitle>
            <span className="text-white">Payment Being Approved</span>
          </SectionTitle>
          <dl className="mt-3 space-y-1.5 text-[12.5px]">
            <div className="flex justify-between">
              <dt className="text-white/60">Invoice</dt>
              <dd className="font-semibold">{details.invoiceNumber}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-white/60">Matched Quantity</dt>
              <dd className="font-semibold">{matchedQty} units</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-white/60">Invoice Total</dt>
              <dd className="font-semibold">{formatINR(details.charges.total)}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-white/60">Payment Status</dt>
              <dd className="flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 rounded-full bg-white/70" />
                {payment.status === 'Paid' ? 'Paid' : payment.status === 'Review' ? 'In Review' : 'Pending Approval'}
              </dd>
            </div>
          </dl>
          <p className="mt-3 flex items-center gap-1.5 text-[11.5px] text-white/50">
            <Check size={12} /> Approval is based on the invoiced quantity matching the received quantity.
          </p>
        </div>
      </div>
    </Drawer>
  );
}
